// Explanations shown as tooltips on every option. Keep them precise: the operator is a LiDAR specialist.
export const TIPS: Record<string, string> = {
  aglM: 'Nominal height above ground the survey is planned for. Line spacing comes from the swath at this height. Each waypoint is set at least this high above the HIGHEST terrain within ±corridor along both adjacent legs, so over lower ground the real AGL is higher (see "AGL on lines" and the overlap figures).',
  speedMs: 'Ground speed on the data lines. Along-track point density ∝ 1 / speed. Also sets the figure-8 radius: r = v² / (g · tan bank).',
  fovDeg: 'Usable across-track field of view of the L3 in the scan mode you will fly, after any edge trimming in processing. Swath = 2 · AGL · tan(FOV / 2).',
  sidelapPct: 'Planned overlap between neighbouring strips at nominal AGL. Line spacing = swath × (1 − sidelap). 50 % gives every point on the ground two strips, which helps strip adjustment and fills occlusions. Over lower ground the swath widens, so achieved sidelap only goes up.',
  courseDeg: 'Line heading in degrees clockwise from true north. Lines are flown back and forth (serpentine). "Optimise course" chooses this for you.',
  runInM: 'Straight distance flown on the line axis before the block edge, so speed, heading and attitude are settled before data starts, and the trajectory solution is not disturbed by the turn.',
  runOutM: 'Straight distance beyond the block edge before the turn, so the bank happens outside the block.',
  wpSpacingM: 'Maximum spacing between waypoints along a line. Shorter spacing lets heights follow the terrain more closely (more even AGL and density) at the cost of more waypoints.',
  corridorM: 'Lateral buffer each side of the track used when finding the highest terrain under each leg. Covers cross-track drift and DEM error beside the line.',
  maxGradient: 'Maximum height change per metre flown between waypoints (0.15 = 15 %). At 17 m/s, 15 % ≈ 2.6 m/s vertical. Waypoints are only ever RAISED to meet it, so crossing steep terrain pushes AGL up. Keep it within the aircraft\'s comfortable climb rate at line speed.',
  fig8BankDeg: 'Design bank angle for the IMU-excitation figure-8 flown before the first line and before any resume. Radius = v² / (g · tan bank). In waypoint mode the aircraft may slow in the loops, so the real bank will be lower; check in the simulator.',
  takeoffSecurityM: 'DJI "take-off security height": after take-off the aircraft climbs VERTICALLY to this height above the take-off point before heading for the route. Set it to clear trees, masts and buildings around home.',
  flyToMode: 'How the aircraft flies from take-off to the first waypoint (DJI flyToWaylineMode).\n• Safely: climb vertically to the higher of the security height and the first-waypoint height, then fly LEVEL to the route. Safest over rising ground.\n• Point to point: climb to the security height, then fly a straight SLOPING line to the first waypoint. Shorter, but it can cut into terrain between home and the route. The transit check below catches that.',
  transitSpeedMs: 'Speed from home to the route start (DJI globalTransitionalSpeed). Also used for the return-to-home time estimate.',
  rthHeightM: 'Return-to-home altitude above the TAKE-OFF point. If the aircraft is higher when RTH triggers it keeps its current height. Leave empty to use the recommended value: the lowest height that clears terrain + min clearance on the straight line home from every waypoint. The M400\'s own RTH logic may differ; confirm the setting on the aircraft.',
  minClearanceM: 'Minimum terrain clearance required on the take-off transit and on every straight-line RTH path (terrain within ±corridor).',
  resOn: 'Build a route that picks up a job after data stopped (battery, weather, a recording fault). It never relies on Pilot 2 breakpoints.',
  resLine: 'The line where good data stopped. The new route restarts ONE LINE EARLIER for overlap, with a fresh figure-8 and recording started on the approach.',
  resSpeed: 'Line speed for the resumed part, e.g. slower in wind. The figure-8 radius follows the new speed.',
  optCourse: 'Without terrain: fewest lines, then shortest line distance. With terrain: minimises route length × (mean line AGL ÷ nominal AGL). Point density falls roughly as 1/AGL, so this favours lines along slopes, where heights stay even, over lines across ridges, where the gradient limit pushes AGL up.',
  fetchDem: 'Downloads Copernicus GLO-30 (30 m, orthometric heights) for the block plus a 2 km buffer from OpenTopography with your API key. GLO-30 avoids the pitch spikes that DJI\'s default ASTER/SRTM terrain causes.',
  setHome: 'Click, then click the map where you will take off. You can drag the home marker afterwards. The home ground height comes from the loaded DEM.',
  view3d: 'Tilt into 3D. Routes are drawn at their true heights, with drop lines to the ground on the data lines. The 3D ground is AWS Terrain Tiles, for display only; the planning uses the DEM you loaded.',
  swaths: 'Show LiDAR strip footprints at each waypoint\'s real AGL. Where strips overlap the colour gets darker; with 50 % sidelap every point should be covered twice.',
  exportJson: 'Download the computed mission (waypoints, heights, speeds, actions, take-off settings) as JSON. The KMZ writer waits for the RC sample export.',
};
