// Generates RC import-test KMZs (IMPORT / SIMULATOR ONLY, DO NOT FLY) near the Pilot 2 sample site.
//   node tools/make-import-tests.ts            (needs VITE_OPENTOPO_KEY in apps/web/.env.development.local)
// Output: samples/generated/*.kmz + README.md describing each file.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import {
  planLines, buildRoute, applyHeights, readGeoTiff, rasterElev, bufferedBbox, openTopoUrl, writeWpml, writeKmz,
  type LonLat, type Route, type FlightWp,
} from '../packages/core/src/index.ts';

const root = new URL('..', import.meta.url);
const env = readFileSync(new URL('apps/web/.env.development.local', root), 'utf8');
const key = env.match(/^VITE_OPENTOPO_KEY=(.+)$/m)?.[1].trim();
if (!key) throw new Error('VITE_OPENTOPO_KEY missing');

// Centre = the first waypoint of the local (gitignored) Pilot 2 sample, so no site coordinates live in the repo.
const sampleWpml = readFileSync(new URL('samples/extracted/waypoint/wpmz/waylines.wpml', root), 'utf8');
const [lon0, lat0] = sampleWpml.match(/<coordinates>\s*([\d.-]+),([\d.-]+)/)!.slice(1).map(Number);
const m = 1 / 111320, k = Math.cos(lat0 * Math.PI / 180);
const P = (x: number, y: number): LonLat => [lon0 + x * m / k, lat0 + y * m];
const rect = (w: number, h: number): LonLat[] => [P(-w / 2, -h / 2), P(w / 2, -h / 2), P(w / 2, h / 2), P(-w / 2, h / 2)];

const bbox = bufferedBbox(rect(6000, 6000), 2500);
const res = await fetch(openTopoUrl(bbox, key, 'COP30'));
if (!res.ok) throw new Error('OpenTopography ' + res.status);
const elev = rasterElev(await readGeoTiff(await res.arrayBuffer()));

const out = new URL('samples/generated/', root);
mkdirSync(out, { recursive: true });
const opts = (speed: number) => ({
  takeoff: { flyToMode: 'safely' as const, takeoffSecurityM: 60, transitSpeedMs: 15 },
  lidar: { samplingRate: 350000, returnMode: 'sedecupleReturn' as const, scanningMode: 'repetitive' as const, modelColoring: true },
  djiImuCalibration: true, rgbPhotoSpacingM: 25, gimbalStartGroup: true, _speed: speed,
});
const rows: string[] = [];
async function emit(name: string, route: Route<FlightWp>, note: string) {
  const files = writeWpml(route, opts(route.speedMs));
  writeFileSync(new URL(name, out), await writeKmz(files));
  const hs = route.wps.map(w => w.h);
  rows.push(`| \`${name}\` | ${route.wps.length} | ${(files.distanceM / 1000).toFixed(1)} km | ${Math.min(...hs).toFixed(0)}–${Math.max(...hs).toFixed(0)} m | ${note} |`);
}

// 1. Small real survey: 600 × 400 m, 100 m AGL, 10 m/s, figure-8, 350 kHz, DJI IMU calibration, RGB photos.
{
  const plan = planLines(rect(600, 400), { aglM: 100, speedMs: 10, courseDeg: 0, wpSpacingM: 100 });
  await emit('test-01-small-l3-survey.kmz', applyHeights(plan, buildRoute(plan), elev),
    'Small L3 survey on real GLO-30 terrain: figure-8, start/stop point cloud, DJI IMU calibration, RGB photos. Check it imports, draws correctly, and shows the L3 actions.');
}
// 2. Waypoint-cap probes: grow a square block (50 m WP spacing) until the route reaches the target count.
for (const target of [250, 500, 1000, 2000, 5000]) {
  let route: Route<FlightWp> | null = null;
  for (let side = 400; side <= 12000; side += 100) {
    const plan = planLines(rect(side, side), { aglM: 100, speedMs: 10, courseDeg: 0, wpSpacingM: 50 });
    route = applyHeights(plan, buildRoute(plan), elev);
    if (route.wps.length >= target) break;
  }
  await emit(`test-cap-${String(target).padStart(4, '0')}.kmz`, route!, `Waypoint-cap probe (≥${target}). Import only: does Pilot 2 accept it?`);
}

writeFileSync(new URL('README.md', out), `# Generated import tests: IMPORT / SIMULATOR ONLY, DO NOT FLY

Generated by \`node tools/make-import-tests.ts\` from the planner's WPML writer (built from your Pilot 2 samples),
centred on the first waypoint of \`m400-l3-waypoint-reference.kmz\`, on real Copernicus GLO-30 terrain.
Heights are EGM96 in template.kml and WGS84 ellipsoidal in waylines.wpml, exactly as Pilot 2 writes them.

| File | Waypoints | Length | Height (EGM96) | What to check |
|---|---|---|---|---|
${rows.join('\n')}

## How to test (Pilot 2)
1. Copy the files to the RC (USB → File transfer) → Pilot 2 → Flight Route → **Import route** (KMZ).
2. For each file note: imports OK / error message; the route draws where expected; for test-01 open a waypoint and check the
   actions (start point cloud recording on WP1, IMU calibration, stop on the last).
3. For the cap probes, the largest file that imports cleanly is our **max waypoints per route**. Tell me the number.
4. Optional, simulator only: run test-01 in the DJI simulator with props off and check the L3 starts recording.
`);
console.log(rows.join('\n'));
